// Central data file for all projects
export interface Project {
  id: number;
  name: string;
  category: string;
  year: number;
  description: string;
  role: string[];
  services: string[];
  image: string;
  color: string;
  url: string;
}

export const PROJECTS: Project[] = [
  {
    id: 1,
    name: "HEONA MEDIA",
    category: "STUDIO",
    year: 2026,
    description: "A digital home for a creative media studio, built around bold visuals, movement and a distinctive purple identity. Every scroll triggers a new perspective.",
    role: ["Creative Direction", "Web Design", "Development"],
    services: ["Branding", "Web Design", "Motion"],
    image: "/project_heona.webp",
    color: "#8B5CF6",
    url: "https://www.heonamedia.com/",
  },
  {
    id: 2,
    name: "MINH AN STUDIO",
    category: "STUDIO",
    year: 2026,
    description: "A boutique creative studio portfolio — clean editorial grid, motion-led transitions and a strong visual identity that lets the work speak for itself.",
    role: ["Art Direction", "Web Design", "Development"],
    services: ["Web Design", "Development", "Motion"],
    image: "/project_heona.webp",
    color: "#A78BFA",
    url: "https://minh-an-studio.vercel.app/",
  },
  {
    id: 3,
    name: "NOVA CREATIVE AGENCY",
    category: "STUDIO",
    year: 2026,
    description: "A bold agency site for a full-service creative team. Dynamic layout, strong typography system and an interactive portfolio showcase.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_heona.webp",
    color: "#818CF8",
    url: "https://nova-creative-agency.vercel.app/",
  },
  {
    id: 4,
    name: "VELOCITY DIGITAL",
    category: "STUDIO",
    year: 2025,
    description: "A digital agency landing page built for speed — both visually and technically. Fast-paced layout, high-contrast palette, direct messaging.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_heona.webp",
    color: "#6EE7B7",
    url: "https://velocity-digital.vercel.app/",
  },
  {
    id: 5,
    name: "LIQUID AUTOMATION",
    category: "CORPORATE",
    year: 2025,
    description: "A SaaS / automation platform website. Clean enterprise UI, clear feature sections, and a conversion-first structure built for B2B audiences.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development", "UI/UX"],
    image: "/project_studio.webp",
    color: "#38BDF8",
    url: "https://liquid-automation.vercel.app/",
  },
  {
    id: 6,
    name: "BUSINESS AUTOMATION",
    category: "CORPORATE",
    year: 2025,
    description: "Corporate landing page for a business process automation firm. Structured, professional and engineered to generate qualified leads.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_studio.webp",
    color: "#64748B",
    url: "https://business-automation-ten.vercel.app/",
  },
  {
    id: 7,
    name: "EMERALD ESTATE",
    category: "REAL ESTATE",
    year: 2025,
    description: "Premium property developer website. Aspirational imagery, architectural precision and clear calls-to-action designed for high-value listings.",
    role: ["Art Direction", "Web Design", "Development"],
    services: ["Web Design", "Development", "SEO"],
    image: "/project_realestate.webp",
    color: "#34D399",
    url: "https://emerald-estate.vercel.app/",
  },
  {
    id: 8,
    name: "NHÀ KHOA TMC",
    category: "HEALTHCARE",
    year: 2025,
    description: "Modern dental clinic website — clean, clinical and warm. Designed to build trust, showcase services and drive appointment bookings.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development", "SEO"],
    image: "/project_clinic.webp",
    color: "#22D3EE",
    url: "https://nha-khoa-t-m-c.vercel.app/",
  },
  {
    id: 9,
    name: "SENMOC SPA",
    category: "BEAUTY",
    year: 2025,
    description: "A serene, luxurious spa website. Muted palette, slow transitions and a sense of calm that begins the moment you land on the page.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Photography Direction"],
    image: "/project_clinic.webp",
    color: "#F9A8D4",
    url: "https://senmocspa.vercel.app/",
  },
  {
    id: 10,
    name: "LULLABY MASSAGE",
    category: "BEAUTY",
    year: 2025,
    description: "Wellness and massage brand website. Soft, inviting atmosphere conveyed through careful typography, warm tones and considered white space.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_clinic.webp",
    color: "#C4B5FD",
    url: "https://lullaby-massage.vercel.app/",
  },
  {
    id: 11,
    name: "LULLABY MASSAGE II",
    category: "BEAUTY",
    year: 2025,
    description: "An updated version of the Lullaby Massage brand experience — refined layout, smoother interactions and a more polished booking flow.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_clinic.webp",
    color: "#DDD6FE",
    url: "https://lullaby-massage-l2la.vercel.app/",
  },
  {
    id: 12,
    name: "ANNA NGỌC ANH BRANDING",
    category: "BEAUTY",
    year: 2024,
    description: "Personal branding and portfolio site for a beauty professional. Elegant, feminine and built around a signature visual identity.",
    role: ["Branding", "Web Design", "Development"],
    services: ["Branding", "Web Design"],
    image: "/project_clinic.webp",
    color: "#F472B6",
    url: "https://anna-ng-c-anh-branding.vercel.app/",
  },
  {
    id: 13,
    name: "MAISON OR PERFUME",
    category: "BEAUTY",
    year: 2024,
    description: "Luxury perfume boutique — an immersive scent experience translated into digital form. Gold tones, editorial photography, premium feel throughout.",
    role: ["Art Direction", "Web Design", "Development"],
    services: ["Art Direction", "Web Design", "Development"],
    image: "/project_clinic.webp",
    color: "#FCD34D",
    url: "https://maison-or-luxury-perfume-boutique.vercel.app/",
  },
  {
    id: 14,
    name: "LUXE BIJOUX",
    category: "BEAUTY",
    year: 2024,
    description: "Fine jewelry e-commerce and brand site. Refined grid layouts, macro product photography direction and an effortlessly luxurious checkout journey.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development", "E-commerce"],
    image: "/project_clinic.webp",
    color: "#FDE68A",
    url: "https://luxe-bijoux.vercel.app/",
  },
  {
    id: 15,
    name: "VELORAH",
    category: "BEAUTY",
    year: 2024,
    description: "A beauty brand site built around ritual and self-care. Botanical imagery, earthy tones and a deeply intentional layout.",
    role: ["Art Direction", "Web Design"],
    services: ["Art Direction", "Web Design", "Development"],
    image: "/project_clinic.webp",
    color: "#86EFAC",
    url: "https://velorah-pi.vercel.app/",
  },
  {
    id: 16,
    name: "THE CURATED EARTH",
    category: "BEAUTY",
    year: 2024,
    description: "An eco-conscious beauty and lifestyle brand. Natural palette, sustainable narrative and a gentle shopping experience that reflects the brand's values.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_clinic.webp",
    color: "#6EE7B7",
    url: "https://the-curated-earth.vercel.app/",
  },
  {
    id: 17,
    name: "LUXORA ELEGANCE",
    category: "FASHION",
    year: 2024,
    description: "A fashion e-commerce brand with timeless elegance. Structured editorial grid, model photography direction and an aspirational luxury feel.",
    role: ["Art Direction", "Web Design", "Development"],
    services: ["Art Direction", "Web Design", "Development"],
    image: "/project_studio.webp",
    color: "#E2E8F0",
    url: "https://luxora-timeless-elegance.vercel.app/",
  },
  {
    id: 18,
    name: "STREET IMPACT FASHION",
    category: "FASHION",
    year: 2024,
    description: "A streetwear brand built for culture. Bold type, high-contrast visuals and a drop-style e-commerce model designed for hype and conversion.",
    role: ["Art Direction", "Web Design"],
    services: ["Art Direction", "Web Design", "Development"],
    image: "/project_studio.webp",
    color: "#F87171",
    url: "https://street-impact-fashion.vercel.app/",
  },
  {
    id: 19,
    name: "FASHION SEVEN",
    category: "FASHION",
    year: 2023,
    description: "A contemporary fashion brand website. Clean editorial grid, campaign imagery and a refined shopping experience for a discerning customer.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_studio.webp",
    color: "#CBD5E1",
    url: "https://fashion-seven-beta.vercel.app/",
  },
  {
    id: 20,
    name: "KINETIC NOIR",
    category: "FASHION",
    year: 2023,
    description: "A dark, motion-driven fashion portfolio. Cinematic transitions, high-contrast imagery and a visual language that challenges convention.",
    role: ["Art Direction", "Web Design", "Development"],
    services: ["Art Direction", "Web Design", "Motion"],
    image: "/project_studio.webp",
    color: "#94A3B8",
    url: "https://kinetic-noir-tau.vercel.app/",
  },
  {
    id: 21,
    name: "UNILEARN",
    category: "EDUCATION",
    year: 2023,
    description: "A digital learning platform for university-level students. Clean, functional and aspirational — structured to make studying feel less daunting.",
    role: ["UX Research", "Web Design", "Development"],
    services: ["UX Design", "Web Design", "Development"],
    image: "/project_education.webp",
    color: "#60A5FA",
    url: "https://uni-learn-xi.vercel.app/",
  },
  {
    id: 22,
    name: "ENGLISH NOTE CENTER",
    category: "EDUCATION",
    year: 2023,
    description: "Language learning center website. Clear course structure, warm approachable design and a registration flow optimized for lead generation.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development", "SEO"],
    image: "/project_education.webp",
    color: "#FCD34D",
    url: "https://english-note-center.vercel.app/",
  },
  {
    id: 23,
    name: "NOTEBOOK FLIPS",
    category: "EDUCATION",
    year: 2023,
    description: "A stationery and education brand website. Playful yet structured — communicates creativity and quality for a young student demographic.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_education.webp",
    color: "#F59E0B",
    url: "https://notebook-flips.vercel.app/",
  },
  {
    id: 24,
    name: "GUNDAM ARMORY",
    category: "OTHER",
    year: 2022,
    description: "An online store for Gundam model kit collectors. Detailed product catalogue, community-focused UI and a design that speaks the hobby's language.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development", "E-commerce"],
    image: "/project_studio.webp",
    color: "#FB923C",
    url: "https://gundam-armory.vercel.app/",
  },
  {
    id: 25,
    name: "COSPLAY STORE",
    category: "OTHER",
    year: 2022,
    description: "A cosplay costume and accessories e-commerce store. Vibrant, character-forward visuals with a fun and explorable product browsing experience.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development", "E-commerce"],
    image: "/project_studio.webp",
    color: "#F472B6",
    url: "https://cosplay-store.vercel.app/",
  },
  {
    id: 26,
    name: "CAMERA PRO",
    category: "OTHER",
    year: 2022,
    description: "Photography equipment store — technical spec-heavy product pages combined with an aspirational brand feel for serious photographers.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_studio.webp",
    color: "#64748B",
    url: "https://camerapro-eight.vercel.app/",
  },
  {
    id: 27,
    name: "NEON GLIDE SKATE",
    category: "OTHER",
    year: 2022,
    description: "A patin / inline skating brand website. Neon energy, dynamic motion elements and a youth-first design that captures the sport's culture.",
    role: ["Art Direction", "Web Design"],
    services: ["Art Direction", "Web Design", "Development"],
    image: "/project_studio.webp",
    color: "#A3E635",
    url: "https://neon-glide-patin.vercel.app/",
  },
  {
    id: 28,
    name: "WHITE WEB DESIGN",
    category: "STUDIO",
    year: 2022,
    description: "A clean, minimal web design studio portfolio. White space, careful typography and a grid that lets projects breathe and demand attention.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_heona.webp",
    color: "#F1F5F9",
    url: "https://white-web-design.vercel.app/",
  },
  {
    id: 29,
    name: "PORTFOLIO BK58",
    category: "STUDIO",
    year: 2022,
    description: "A personal developer/designer portfolio with a confident dark aesthetic. Strong typographic hierarchy and a focused presentation of selected work.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_heona.webp",
    color: "#818CF8",
    url: "https://portfolio-black-six-58.vercel.app/",
  },
  {
    id: 30,
    name: "GLASS PORTFOLIO",
    category: "STUDIO",
    year: 2022,
    description: "An experimental glassmorphism portfolio — exploring depth, light and layering as a visual language for a multidisciplinary creative.",
    role: ["Creative Direction", "Web Design", "Development"],
    services: ["Web Design", "Development", "Motion"],
    image: "/project_heona.webp",
    color: "#7DD3FC",
    url: "https://glass-morphism-portfolio.vercel.app/",
  },
  {
    id: 31,
    name: "GMB FURNITURE",
    category: "CORPORATE",
    year: 2022,
    description: "Corporate brand site for a Vietnamese furniture manufacturer. Product-forward layout, clean photography direction and a reliable, professional feel.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_realestate.webp",
    color: "#D97706",
    url: "https://g-m-b-u-tr-c.vercel.app/",
  },
  {
    id: 32,
    name: "WEB DESIGN STUDIO",
    category: "STUDIO",
    year: 2022,
    description: "A showcase portfolio for a web design studio — editorial layout, project case studies and a clean visual system that communicates craft and intention.",
    role: ["Web Design", "Development"],
    services: ["Web Design", "Development"],
    image: "/project_heona.webp",
    color: "#A78BFA",
    url: "https://web-design-studio-mauve.vercel.app/",
  },
];

export const CATEGORIES = ["ALL", "STUDIO", "CORPORATE", "HEALTHCARE", "EDUCATION", "BEAUTY", "FASHION", "REAL ESTATE", "OTHER"];

export const FEATURED_PROJECTS = [1, 7, 8, 9, 17].map(id => PROJECTS.find(p => p.id === id)!);
